import type { NextApiRequest, NextApiResponse } from 'next'

import { AgentUnavailableError, callAgent, isAgentConfigured } from '@/lib/superbase2/agent-client'
import { checkCsrf, requireAuth } from '@/lib/superbase2/auth'
import { getProject, isSuperBase2Enabled, isValidProjectRef } from '@/lib/superbase2/projects'
import { toDbUrlTemplate } from '@/lib/superbase2/response-helpers'

/**
 * GET  /api/superbase2/projects/{ref}/keys           — return current keys
 * POST /api/superbase2/projects/{ref}/keys?rotate=1  — rotate JWT secret + API keys
 *
 * The manifest stores per-project secrets generated by `superbase2.sh`. Self-hosted
 * Studio's stock API Keys / JWT Keys settings pages call Cloud-only control-plane
 * endpoints (signing-key rotation, JWKS), so this route is the SB2-native way to
 * surface and rotate keys for a project.
 *
 * Rotation is delegated to the sb2-agent which runs `superbase2.sh rotate-keys`:
 * the script regenerates the secrets, rewrites the project's .env, updates the
 * Postgres `app.settings.jwt_secret` GUC, syncs the manifest, rebuilds Kong, and
 * restarts the per-project containers so they pick up the new PROJECT_JWT_SECRET.
 */
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (!isSuperBase2Enabled()) {
    return res.status(404).json({ error: { message: 'SuperBase² is not enabled' } })
  }
  if (!(await requireAuth(req, res))) return

  const ref = req.query.ref as string
  if (!isValidProjectRef(ref)) {
    return res.status(404).json({ error: { message: 'Project not found' } })
  }

  if (req.method === 'GET') {
    const project = getProject(ref)
    if (!project) {
      return res.status(404).json({ error: { message: 'Project not found' } })
    }
    return res.status(200).json(buildKeysPayload(project))
  }

  if (req.method === 'POST') {
    if (!checkCsrf(req, res)) return

    const project = getProject(ref)
    if (!project) {
      return res.status(404).json({ error: { message: 'Project not found' } })
    }

    if (!isAgentConfigured()) {
      return res.status(503).json({
        error: {
          message:
            'sb2-agent is not configured on this server. Set SB2_AGENT_URL and ' +
            'SB2_AGENT_TOKEN and redeploy Studio to enable key rotation.',
        },
      })
    }

    try {
      // Two-phase rotation:
      //   1. Sync: agent runs `rotate-keys` with SB2_ROTATE_SKIP_RESTART=1 —
      //      regenerates secrets, rewrites .env, ALTERs the per-DB GUC, syncs
      //      the manifest, rebuilds Kong. Returns in a few seconds.
      //   2. Async: we fire `restart` and don't await — containers reload
      //      with the new PROJECT_JWT_SECRET in 30–90s.
      // The split exists because edge proxies (Coolify Traefik, Cloudflare)
      // typically time out around 30–60s, well below the restart duration.
      // Without the split the browser saw a 502 even though the rotation
      // had succeeded on disk.
      const result = await callAgent('rotate-keys', project.name)
      const ok = Boolean((result as { ok?: boolean }).ok)
      if (!ok) {
        return res.status(500).json({ action: 'rotate-keys', ...result })
      }
      // Re-read the manifest so the response carries the freshly rotated values.
      const updated = getProject(ref)
      if (!updated) {
        return res.status(500).json({ error: { message: 'Project disappeared after rotation' } })
      }

      // Fire-and-forget the restart. Errors are logged but not surfaced —
      // the rotation itself already succeeded; the worst case is the user
      // restarts the project manually.
      callAgent('restart', project.name).catch((err) => {
        console.error(`[SuperBase²] post-rotation restart failed for '${project.name}':`, err)
      })

      return res.status(200).json({
        ...buildKeysPayload(updated),
        restart_pending: true,
      })
    } catch (err) {
      if (err instanceof AgentUnavailableError) {
        return res.status(503).json({ error: { message: err.message } })
      }
      console.error('[SuperBase²] key rotation failed:', err)
      return res.status(500).json({ error: { message: 'Failed to rotate keys' } })
    }
  }

  res.setHeader('Allow', ['GET', 'POST'])
  return res.status(405).json({ error: { message: `Method ${req.method} Not Allowed` } })
}

function buildKeysPayload(project: ReturnType<typeof getProject> & object) {
  const publicUrl = (process.env.SUPABASE_PUBLIC_URL || '').replace(/\/$/, '')
  return {
    ref: project.ref,
    name: project.name,
    url: publicUrl ? `${publicUrl}/project/${project.ref}` : null,
    anon_key: project.anon_key,
    service_role_key: project.service_role_key,
    jwt_secret: project.jwt_secret,
    db_url: toDbUrlTemplate(project),
  }
}
